### ISSUE TITLE
clipboard.get_clipbard() function crashes sometimes

### ISSUE THREAD

**Issue by snowboard975** [autokey-py3/autokey#8]
I use Lubuntu 14.04 (32-bit) and autokey-py3 0.90.4

When I open a text editor named, "Untitled" and run below code in autokey-gtk, it stops randomly without any error before ending the full 1000 loop.

``` python
#--------------------------------------------------------------
clipboard.fill_clipboard("tmp")
window.activate("Untitled")
i=0
while (i<1000):
    text1=clipboard.get_clipboard()
    keyboard.send_keys(str(i))
    keyboard.send_keys("<ctrl>+v")
    keyboard.send_keys("<enter>")
    i=i+1
#----------------------------------------------------------
```

And the terminal that shows debug information because of autokey-gtk -l command that I ran before, shows the following lines at last. It stopped at the 29th iteration and doesn't show any error, which is also strange. And the number of iteration when it stops is random. It is sometimes 112, 353, or 911, and, in most cases, it cannot reach the final 1000th loop

``` python
2015-05-20 16:30:13,652 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:13,664 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:13,683 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:13,687 DEBUG - interface - Sending string: '24'
2015-05-20 16:30:13,721 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:13,745 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:13,827 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:13,833 DEBUG - interface - Sending string: '25'
2015-05-20 16:30:13,866 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:13,907 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:13,987 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:13,992 DEBUG - interface - Sending string: '26'
2015-05-20 16:30:14,037 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:14,051 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:14,092 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:14,130 DEBUG - interface - Sending string: '27'
2015-05-20 16:30:14,233 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:14,251 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:14,287 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:14,312 DEBUG - interface - Sending string: '28'
2015-05-20 16:30:14,373 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:14,378 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:14,395 DEBUG - interface - Send special key: ['<enter>']
2015-05-20 16:30:14,399 DEBUG - interface - Sending string: '29'
2015-05-20 16:30:14,429 DEBUG - interface - Send modified key: modifiers: ['<ctrl>'] key: v
2015-05-20 16:30:14,463 DEBUG - interface - Sending string: 'tmp'
2015-05-20 16:30:14,499 DEBUG - interface - Send special key: ['<enter>']
```

**Comment by gggtest** [comment]
i think u need some short delay (time.sleep) between keyboard.send_keys.

**Comment by snowboard975** [comment]
I used 0.5 second of delays between every keyboard.send_keys when I found the problem. In other words, I had the problem also with the delays. I removed those delays in the example code just to briefly show you the problem with fast response.

**Comment by troxor** [comment]
Among the debug output, I see a few tracebacks (using a loop of 100)

```Traceback (most recent call last):
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 143, in __eventLoop
    method(*args)
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 612, in __sendString
    self.__checkWorkaroundNeeded()
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 898, in __checkWorkaroundNeeded
    if w.match(str_or_bytes_to_str(windowName)) or w.match(windowClass):
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 72, in str_or_bytes_to_str
    raise RuntimeError("x must be str or bytes object, type(x)={}, repr(x)={}".format(type(x), repr(x)))
RuntimeError: x must be str or bytes object, type(x)=<class 'memoryview'>, repr(x)=<memory at 0x7f2f585f9e58>
tmp 24


2016-11-20 23:19:17,091 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 143, in __eventLoop
    method(*args)
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 612, in __sendString
    self.__checkWorkaroundNeeded()
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 896, in __checkWorkaroundNeeded
    windowClass = self.get_window_class(focus)
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 1003, in get_window_class
    return self.__getWinClass(windowvar, traverse)
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/interface.py", line 1015, in __getWinClass
    wmclass = windowvar.get_wm_class()
  File "/home/troxor/.local/lib64/python3.4/site-packages/Xlib/xobject/drawable.py", line 684, in get_wm_class
    value = self.get_full_text_property(Xatom.WM_CLASS, Xatom.STRING)
  File "/home/troxor/.local/lib64/python3.4/site-packages/Xlib/xobject/drawable.py", line 491, in get_full_text_property
    prop.value = prop.value.decode(self._STRING_ENCODING)
AttributeError: 'memoryview' object has no attribute 'decode'



2016-11-20 23:19:17,648 DEBUG - interface - Send special key: ['<enter>']
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, <memory at 0x7f2f584b0c00>)
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03q\x16\x08\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03r\x16#\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03s\x16#\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03t\x168\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03u\x168\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f2f8c0cff60>, b'\x00\x03v\x16P\xd3\xa0\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```

**Comment by snowboard975** [comment]
Dear troxer,

I am sorry, but it is difficult for me to understand your words. Could you explain it in easier words? 

For example,
Does it mean that you found a solution?
Or does it mean that it is not a bug, but I just did something wrong?
Or does it mean that you want me to give you certain feedbacks?

Thank you.

**Comment by troxor** [comment]
It's mostly just notes about the issue, for reference. I was able to reproduce the issue.

**Comment by snowboard975** [comment]
Thank you for note. I am pleased that you could also confirm the problem and found the tracebacks. 
I look forward to seeing the problem to be fixed soon.

**Comment by troxor** [comment]
After taking a deeper look at this, it's somewhat of a pathological example, and not strictly a bug, per se. Even though the send_keys command uses a FIFO queue, the repeated calls to get_clipboard occur asynchronously in another thread. Additionally, inserting the text via actual X clipboard (Ctrl+V) is a less efficient way to achieve the goal and you should use send_keys("theactualtext") instead

Instead, assign clipboard.get_clipboard() to the text1 variable outside the loop, then call send_keys on that variable, like so:

```
text1=clipboard.get_clipboard()
while (i<1000):
    print(text1, str(i))
    keyboard.send_keys(text1)
    keyboard.send_keys(str(i))
```

Otherwise, add a `time.sleep(5)` in there to allow the X Clipboard to "catch up".
